name: CI

on:
  push:

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Before script
        run: |
          chmod +x gradlew
          chmod +x config/checkstyle/checkstyle.sh
          chmod +x gradle/publishAllToMavenLocal.sh

      - name: Run Gradle command
        run: |
          bash ./gradle/publishAllToMavenLocal.sh
          bash ./config/checkstyle/checkstyle.sh
          ./gradlew test
          ./gradlew assemble

